#include <furi.h>

/* generated by fbt from .png files in images folder */
#include <see_and_say_icons.h>

int32_t see_and_say_app(void* p) {
    UNUSED(p);
    FURI_LOG_I("TEST", "Hello world");
    FURI_LOG_I("TEST", "I'm see_and_say!");

    return 0;
}
